export * from './area.service';
import { AreaService } from './area.service';
export * from './areaFormacao.service';
import { AreaFormacaoService } from './areaFormacao.service';
export * from './competencia.service';
import { CompetenciaService } from './competencia.service';
export * from './concursoCategoria.service';
import { ConcursoCategoriaService } from './concursoCategoria.service';
export * from './concursoCategoriaCandidatura.service';
import { ConcursoCategoriaCandidaturaService } from './concursoCategoriaCandidatura.service';
export * from './concursoCategoriaCandidaturaAnexo.service';
import { ConcursoCategoriaCandidaturaAnexoService } from './concursoCategoriaCandidaturaAnexo.service';
export * from './concursoCategoriaFase.service';
import { ConcursoCategoriaFaseService } from './concursoCategoriaFase.service';
export * from './curso.service';
import { CursoService } from './curso.service';
export * from './entidade.service';
import { EntidadeService } from './entidade.service';
export * from './entidadeConcurso.service';
import { EntidadeConcursoService } from './entidadeConcurso.service';
export * from './experienciaProfissional.service';
import { ExperienciaProfissionalService } from './experienciaProfissional.service';
export * from './fase.service';
import { FaseService } from './fase.service';
export * from './funcao.service';
import { FuncaoService } from './funcao.service';
export * from './habilitacao.service';
import { HabilitacaoService } from './habilitacao.service';
export * from './habilitacaoNivel.service';
import { HabilitacaoNivelService } from './habilitacaoNivel.service';
export * from './idioma.service';
import { IdiomaService } from './idioma.service';
export * from './instituicao.service';
import { InstituicaoService } from './instituicao.service';
export * from './paises.service';
import { PaisesService } from './paises.service';
export * from './perfil.service';
import { PerfilService } from './perfil.service';
export * from './perfilAnexo.service';
import { PerfilAnexoService } from './perfilAnexo.service';
export * from './perfilCompetencia.service';
import { PerfilCompetenciaService } from './perfilCompetencia.service';
export * from './perfilIdioma.service';
import { PerfilIdiomaService } from './perfilIdioma.service';
export * from './tipoAnexo.service';
import { TipoAnexoService } from './tipoAnexo.service';
export const APIS = [AreaService, AreaFormacaoService, CompetenciaService, ConcursoCategoriaService, ConcursoCategoriaCandidaturaService, ConcursoCategoriaCandidaturaAnexoService, ConcursoCategoriaFaseService, CursoService, EntidadeService, EntidadeConcursoService, ExperienciaProfissionalService, FaseService, FuncaoService, HabilitacaoService, HabilitacaoNivelService, IdiomaService, InstituicaoService, PaisesService, PerfilService, PerfilAnexoService, PerfilCompetenciaService, PerfilIdiomaService, TipoAnexoService];
