export * from './bolsa.model';
export * from './city.model';
export * from './filterItem.model';
export * from './bolseiro.model';
export * from './instituicao-ensino-curso.model';
export * from './instituicao-ensino-tipo-bolsa.model';
export * from './instituicao-ensino.model';
export * from './provincia.model';
export * from './tipo-bolsa.model';
export * from './provincia.model';
export * from './utilizador.model'
