/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AreaFormacao } from './areaFormacao';
import { Retorno } from './retorno';


export interface AreaFormacaoResponse { 
    data?: AreaFormacao;
    retorno?: Retorno;
}

