/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Funcao } from './funcao';


export interface Area { 
    id?: number;
    designacao?: string | null;
    readonly funcoes?: Array<Funcao> | null;
}

