/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Area } from './area';
import { Retorno } from './retorno';


export interface AreaResponse { 
    data?: Area;
    retorno?: Retorno;
}

