/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Curso } from './curso';


export interface AreaFormacao { 
    id?: number;
    designacao?: string | null;
    cursos?: Array<Curso> | null;
}

