/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Retorno } from './retorno';


export interface BooleanResponse { 
    data?: boolean;
    retorno?: Retorno;
}

