/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Competencia } from './competencia';
import { Retorno } from './retorno';


export interface CompetenciaResponse { 
    data?: Competencia;
    retorno?: Retorno;
}

