/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Perfil } from './perfil';


export interface Competencia { 
    id?: number;
    designacao?: string | null;
    readonly perfis?: Array<Perfil> | null;
}

