/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConcursoCategoriaCandidaturaAnexo } from './concursoCategoriaCandidaturaAnexo';
import { Retorno } from './retorno';


export interface ConcursoCategoriaCandidaturaAnexoResponse { 
    data?: ConcursoCategoriaCandidaturaAnexo;
    retorno?: Retorno;
}

