/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipoAnexo } from './tipoAnexo';
import { ConcursoCategoriaCandidatura } from './concursoCategoriaCandidatura';


export interface ConcursoCategoriaCandidaturaAnexo { 
    concursoCategoriaCandidaturaID?: number;
    tipoAnexoID?: number;
    uid?: string | null;
    nome?: string | null;
    extensao?: string | null;
    contentType?: string | null;
    anexo?: string | null;
    concursoCategoriaCandidatura?: ConcursoCategoriaCandidatura;
    tipoAnexo?: TipoAnexo;
}

