/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConcursoCategoriaFase } from './concursoCategoriaFase';
import { Retorno } from './retorno';


export interface ConcursoCategoriaFaseResponse { 
    data?: ConcursoCategoriaFase;
    retorno?: Retorno;
}

