/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConcursoCategoria } from './concursoCategoria';
import { Perfil } from './perfil';
import { ConcursoCategoriaCandidaturaAnexo } from './concursoCategoriaCandidaturaAnexo';
import { EstadoConcursoCandidaturaEnum } from './estadoConcursoCandidaturaEnum';


export interface ConcursoCategoriaCandidatura { 
    id?: number;
    concursoCategoriaID?: number;
    perfilID?: number;
    dataCandidatura?: string | null;
    estado?: EstadoConcursoCandidaturaEnum;
    perfil?: Perfil;
    concursoCategoria?: ConcursoCategoria;
    concursoCategoriaCandidaturaAnexos?: Array<ConcursoCategoriaCandidaturaAnexo> | null;
}
export namespace ConcursoCategoriaCandidatura {
}


