/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Retorno } from './retorno';
import { Curso } from './curso';


export interface CursoResponse { 
    data?: Curso;
    retorno?: Retorno;
}

