/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Retorno } from './retorno';
import { Entidade } from './entidade';


export interface EntidadeResponse { 
    data?: Entidade;
    retorno?: Retorno;
}

