/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Retorno } from './retorno';
import { Entidade } from './entidade';


export interface EntidadeICollectionPagedResponse { 
    data?: Array<Entidade> | null;
    retorno?: Retorno;
    pageSize?: number;
    pageNumber?: number;
    totalPages?: number;
    totalRecords?: number;
    records?: number;
    nextPage?: string | null;
    previousPage?: string | null;
    firstPage?: string | null;
    lastPage?: string | null;
}

