/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EstadoConcursoCandidaturaEnum = 1 | 2 | 3 | 4 | 5 | 6;

export const EstadoConcursoCandidaturaEnum = {
    NUMBER_1: 1 as EstadoConcursoCandidaturaEnum,
    NUMBER_2: 2 as EstadoConcursoCandidaturaEnum,
    NUMBER_3: 3 as EstadoConcursoCandidaturaEnum,
    NUMBER_4: 4 as EstadoConcursoCandidaturaEnum,
    NUMBER_5: 5 as EstadoConcursoCandidaturaEnum,
    NUMBER_6: 6 as EstadoConcursoCandidaturaEnum
};

