/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Instituicao } from './instituicao';
import { Perfil } from './perfil';
import { Funcao } from './funcao';
import { Paises } from './paises';


export interface ExperienciaProfissional { 
    id?: number;
    nomeInstituicao?: string | null;
    titulo?: string | null;
    descricao?: string | null;
    perfilID?: number;
    instituicaoID?: number;
    funcaoID?: number;
    paisID?: number;
    anoInicio?: string;
    anoTermino?: string | null;
    empregodoActualmente?: boolean;
    perfil?: Perfil;
    instituicao?: Instituicao;
    funcao?: Funcao;
    pais?: Paises;
}

