/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Retorno } from './retorno';
import { Fase } from './fase';


export interface FaseICollectionPagedResponse { 
    data?: Array<Fase> | null;
    retorno?: Retorno;
    pageSize?: number;
    pageNumber?: number;
    totalPages?: number;
    totalRecords?: number;
    records?: number;
    nextPage?: string | null;
    previousPage?: string | null;
    firstPage?: string | null;
    lastPage?: string | null;
}

