/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Funcao } from './funcao';
import { Retorno } from './retorno';


export interface FuncaoResponse { 
    data?: Funcao;
    retorno?: Retorno;
}

