/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Area } from './area';
import { ExperienciaProfissional } from './experienciaProfissional';


export interface Funcao { 
    id?: number;
    designacao?: string | null;
    areaID?: number;
    area?: Area;
    experienciasProfissionais?: Array<ExperienciaProfissional> | null;
}

