/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Paises } from './paises';
import { TipoHabilitacaoEnum } from './tipoHabilitacaoEnum';
import { Curso } from './curso';


export interface Habilitacao { 
    id?: number;
    nomeInstituicao?: string | null;
    designacaoCurso?: string | null;
    tipoHabilitacao?: TipoHabilitacaoEnum;
    perfilID?: number;
    paisID?: number;
    cursoID?: number;
    anoInicio?: string;
    anoTermino?: string | null;
    pais?: Paises;
    curso?: Curso;
}
export namespace Habilitacao {
}


