/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HabilitacaoNivel } from './habilitacaoNivel';
import { Retorno } from './retorno';


export interface HabilitacaoNivelResponse { 
    data?: HabilitacaoNivel;
    retorno?: Retorno;
}

