/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipoHabilitacaoEnum } from './tipoHabilitacaoEnum';
import { Curso } from './curso';


export interface HabilitacaoNivel { 
    id?: number;
    designacao?: string | null;
    tipoHabilitacao?: TipoHabilitacaoEnum;
    readonly cursos?: Array<Curso> | null;
}
export namespace HabilitacaoNivel {
}


