/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerfilIdioma } from './perfilIdioma';


export interface Idioma { 
    id?: number;
    designacao?: string | null;
    perfilIdiomas?: Array<PerfilIdioma> | null;
}

