/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Instituicao } from './instituicao';
import { Retorno } from './retorno';


export interface InstituicaoResponse { 
    data?: Instituicao;
    retorno?: Retorno;
}

