/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExperienciaProfissional } from './experienciaProfissional';
import { SectorEnum } from './sectorEnum';


export interface Instituicao { 
    id?: number;
    designacao?: string | null;
    sector?: SectorEnum;
    experienciasProfissionais?: Array<ExperienciaProfissional> | null;
}
export namespace Instituicao {
}


