/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type NivelCompetenciaEnum = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const NivelCompetenciaEnum = {
    NUMBER_0: 0 as NivelCompetenciaEnum,
    NUMBER_1: 1 as NivelCompetenciaEnum,
    NUMBER_2: 2 as NivelCompetenciaEnum,
    NUMBER_3: 3 as NivelCompetenciaEnum,
    NUMBER_4: 4 as NivelCompetenciaEnum,
    NUMBER_5: 5 as NivelCompetenciaEnum,
    NUMBER_6: 6 as NivelCompetenciaEnum
};

