/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Perfil } from './perfil';
import { Habilitacao } from './habilitacao';
import { ExperienciaProfissional } from './experienciaProfissional';


export interface Paises { 
    id?: number;
    designacao?: string | null;
    sigla?: string | null;
    experienciasProfissionais?: Array<ExperienciaProfissional> | null;
    habilitacoes?: Array<Habilitacao> | null;
    perfis?: Array<Perfil> | null;
}

