/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Paises } from './paises';
import { Retorno } from './retorno';


export interface PaisesResponse { 
    data?: Paises;
    retorno?: Retorno;
}

