/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Idioma } from './idioma';
import { Perfil } from './perfil';


export interface PerfilIdioma { 
    idiomaID?: number;
    perfilID?: number;
    escrita?: number;
    conversacao?: number;
    leitura?: number;
    idioma?: Idioma;
    perfil?: Perfil;
}

