/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerfilCompetencia } from './perfilCompetencia';
import { Habilitacao } from './habilitacao';
import { Paises } from './paises';
import { PerfilIdioma } from './perfilIdioma';
import { PerfilAnexo } from './perfilAnexo';
import { ExperienciaProfissional } from './experienciaProfissional';


export interface Perfil { 
    id?: number;
    userID?: string | null;
    foto?: string | null;
    nif?: string | null;
    nomeCompleto?: string | null;
    filiacaoPai?: string | null;
    filiacaoMae?: string | null;
    dataNascimento?: string;
    email?: string | null;
    telefone1?: string | null;
    telefone2?: string | null;
    sobreMim?: string | null;
    genero?: string | null;
    residencia?: string | null;
    mudariaResidencia?: boolean;
    interessePessoal?: string | null;
    paisID?: number;
    pais?: Paises;
    experienciasProfissionais?: Array<ExperienciaProfissional> | null;
    habilitacoes?: Array<Habilitacao> | null;
    perfilIdiomas?: Array<PerfilIdioma> | null;
    perfilAnexos?: Array<PerfilAnexo> | null;
    perfilCompetencias?: Array<PerfilCompetencia> | null;
}

