/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Competencia } from './competencia';
import { NivelCompetenciaEnum } from './nivelCompetenciaEnum';
import { Perfil } from './perfil';


export interface PerfilCompetencia { 
    id?: number;
    designacao?: string | null;
    nivelCompetencia?: NivelCompetenciaEnum;
    competenciaID?: number;
    perfilID?: number;
    competencia?: Competencia;
    perfil?: Perfil;
}
export namespace PerfilCompetencia {
}


