/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipoAnexo } from './tipoAnexo';
import { Perfil } from './perfil';


export interface PerfilAnexo { 
    id?: number;
    anexo?: string | null;
    uid?: string | null;
    nome?: string | null;
    extensao?: string | null;
    contentType?: string | null;
    tipoAnexoID?: number;
    perfiID?: number;
    tipoAnexo?: TipoAnexo;
    perfil?: Perfil;
}

