/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerfilCompetencia } from './perfilCompetencia';
import { Retorno } from './retorno';


export interface PerfilCompetenciaResponse { 
    data?: PerfilCompetencia;
    retorno?: Retorno;
}

