/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PerfilAnexo } from './perfilAnexo';
import { Retorno } from './retorno';


export interface PerfilAnexoResponse { 
    data?: PerfilAnexo;
    retorno?: Retorno;
}

