/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ResponseCode = 200 | 300 | 404 | 500;

export const ResponseCode = {
    NUMBER_200: 200 as ResponseCode,
    NUMBER_300: 300 as ResponseCode,
    NUMBER_404: 404 as ResponseCode,
    NUMBER_500: 500 as ResponseCode
};

