/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseCode } from './responseCode';


export interface Retorno { 
    codigo?: ResponseCode;
    mensagem?: string | null;
}
export namespace Retorno {
}


