/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SectorEnum = 0 | 1;

export const SectorEnum = {
    NUMBER_0: 0 as SectorEnum,
    NUMBER_1: 1 as SectorEnum
};

