/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TipoHabilitacaoEnum = 0 | 1;

export const TipoHabilitacaoEnum = {
    NUMBER_0: 0 as TipoHabilitacaoEnum,
    NUMBER_1: 1 as TipoHabilitacaoEnum
};

