/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipoAnexo } from './tipoAnexo';
import { Retorno } from './retorno';


export interface TipoAnexoResponse { 
    data?: TipoAnexo;
    retorno?: Retorno;
}

