/**
 * Concurso.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConcursoCategoriaCandidaturaAnexo } from './concursoCategoriaCandidaturaAnexo';


export interface TipoAnexo { 
    id?: number;
    designacao?: string | null;
    concursoCategoriaCandidaturaAnexos?: Array<ConcursoCategoriaCandidaturaAnexo> | null;
}

